### ISSUE TITLE
No fallback fonts for OpenSans

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#1]
Meaning that if the browser is not allowed to load the OpenSans webfonts, it will display the site with Times New Roman (on Windows at least). Maybee a fallback to Arial or similar would be more preferable?

**Comment by andtii** [comment]
@baseic Intresting that the SharePoint styling is not overriding? Or is it for Omnia Admin?

**Comment by baseic** [comment]
@andtii everywhere, I think your font-family is just: OpenSans, so if that is not available for the client it will not fallback on anything until it hits the floor

**Comment by andtii** [comment]
W should fallback to Arial
