### ISSUE TITLE
Queue not functioning in multi-tenant environment

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#2]
Queue names based on 

[QueueTrigger("MyCoolName")] object message

does not seem to work properly in an environment where the same extension is deployed to multiple tenants using the same Omnia host (db instance)

The queues in Omnia database seems to get a Name (PK-contraint) based on the Extension-id + queue name, leading to PK contstraint violation on queue creation in all but the first tenant

**Comment by andtii** [comment]
@khdi We should fix this when we merge in the JobHost scaleout support
