### ISSUE TITLE
Bootstrapping a control manually at a later time

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#35]
Inject a control manually by selector at a later time, i.e. after some DOM element has been rendered by SP  

Expose functionality in Omnia Bootstrapper to getARefistered control and as for bootstrapping by selector. Omnia creates the control container element and injects it in the DOM at the given selector and bootstrap the control.

E.g.:
    var control = Bootstrapper.getRegisteredControls()["7a22effa-cdbc-4eac-9ff8915675547015".toLocaleUpperCase()];

var controlwithContainer =Bootstrapper.CreateControlWithSelectorContainer(control.component);
Bootstrapper.resolveOmniaControls(undefined, undefined, undefined, [controlwithContainer]);

**Comment by andtii** [comment]
@PetterT2  We hade some design on this today and we will implement a delayBootstrap callback on the insertUsingSelector property description where its possible to return a promise, the callback will then fullfill the promise whenever it thinks the control should bootstrap.

**Comment by PetterT2** [comment]
Seems smooth ;)

**Comment by andtii** [comment]
@PetterT2 Implemented and will be in March release Foundation Cycle 8
