### ISSUE TITLE
Purge option for Omnia logs in settings

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#44]
Would be nice with one or several settings for purging of logs from DB. E.g:

Keep INFO logs: unlimited, 1 week, 2 weeks, 1 months, 2 months etc
Keep WARNING logs: unlimited, 1 week, 2 weeks, 1 months, 2 months etc
Keep ERROR logs: unlimited, 1 week, 2 weeks, 1 months, 2 months etc

**Comment by baseic** [comment]
At least a mean to purge logs in any way would be needed. Logs will overflow over time otherwise

**Comment by khdi** [comment]
We will implement a settings for cleanup rules and a job to purge logs.

**Comment by andtii** [comment]
@baseic Good idea, also i think we should have the Info logs as a option you have to turn on and then after a specific time it will be turned off automatically so it wont flood the database. This is how they do it in azure

**Comment by PetterT2** [comment]
@andtii I think that could be one of the options/settings. But I think it would be more helpful to have info always on, but be able to set the keep-time quite low (week/days). Such detailed info is often of interest when trying to figure out a not so frequent error scenario, and help with the understanding about what events took place. Having to turn it on would mean that a serious/infrequent issue would have to happen again after detailed logging has been turned on.  This would make it harder to get accurate logging in these scenarios.

**Comment by andtii** [comment]
@PetterT2 When running onprem that might be fine but in the cloud we can have 28 customers running 28 versions of same extension imagine the flooding if this is always on. In that case it should be off by default for all extensions and manually be started for each tenant

**Comment by andtii** [comment]
We should also log the time when it was set so we can show a warning if it has been on for a longer time

**Comment by andtii** [comment]
Also we should not have unlimited. Maybe a limit of 3 months is enough

**Comment by PetterT2** [comment]
@andtii  I understand, maybe both options could be available?

E.g.
Option1: Purge Info logs after x days (-1 never purge)
Option2: Turn Info logs on for x days (where -1 is always on)

**Comment by andtii** [comment]
@PetterT2 You want to do this?
