### ISSUE TITLE
Configure Managed Paths shown in site template dropdown

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#45]
For on-prem customers (lay aside the "cloud-ready" discussion) it would be convenient if Omnia could support other managed paths than /sites and /teams in site templates.

Can we have a setting somewhere where one can configure which managed paths that should be available for site creation?

This is needed in an on-going customer project

**Comment by khdi** [comment]
@baseic we will add this to Site Templates> Settings in Omnia admin.

**Comment by andtii** [comment]
Managed paths /sites and /teams should be default value. Also this setting should only be visible OnPrem
