### ISSUE TITLE
MDS - do not disable by default

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#48]
Do not disable MDS by default when creating sites through Omnia. 

Instead, make it an option in the Site templates (by enabling that feature for your template).

This since MDS is still much needed on-prem

**Comment by andtii** [comment]
@baseic This has been fixed

**Comment by baseic** [comment]
Is this released, or when will it be releases? We have an installation in QA on friday @andtii @khdi

**Comment by andtii** [comment]
@baseic It has not been released yet, it will be in the Cycle 8 release which is in the end of dev now. We are a bit behind so we will not make it to friday.
