### ISSUE TITLE
Short lived/narrow topic publish/subscribe - Missing unsubscribe

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#49]
(If we stretch the concept of publish/subscribe and support the scenario below it would be helpful in some cases)

In the scope of narrow/short lived subscriptions, meaning a publish/subscription topics that will only get one or a few messages once over time. After having received messages in a subscription it's not likely to get more messages on the subscribed topic. In this case it would be helpful to be able to **unsubscribe** to a topic, i.e. not flooding the underlying Map with topic<->handlingAction never expected to ever get a message again. So an unsubscribe to topic would be helpful.

An alternative (good or bad) to an unsubscribe approach , could be an "in current thread subscription", this would of course be considered more of a "dump all messages now" for messages matching the subscribed topic, i.e. after executing subscribe the subscription the action will have been triggered for all messages currently matching the topic. (No map between Topic and action needs to be kept)

Pseudocode:

List<UserFollowSiteMessage> userFollowMsgs = new List<UserFollowSiteMessage>();

OmniaApi.WorkWith(Ctx.Omnia()).Messaging(IkanoConstants.PublishSubscribe.ClientIds.WebApi).**UseCurrentThread()**.Subscribe<UserFollowSiteMessage>(Constants.PublishSubscribe.Topics.UserFollowSiteMsg + Ctx.Omnia().LoginName, (msg, id) =>
            {
                userFollowMsgs.Add(msg);
            });

//Follow/unfollow sites in the msg's above

We now have messages concerning which sites the user should update it's "follow"/"unfollow" status for, we can now use SharePoints CSOM interface which only supports sites follow in the context of the current user.

**Comment by andtii** [comment]
@PetterT2 The implementer is responsible for unsubscribing on all available servers, maybe by using another message then
