### ISSUE TITLE
OmniaApi.WorkWith(Ctx.Omnia()).Features().GetFeatureActivationStatus - Incorrect status for sitecollection features

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#50]
GetFeatureActivationStatus returns NotActivated for sitecollection feature, but it's activated if checked using GetFeature.

var id = new Guid(IkanoConstants.Features.SiteCollectionCooperationFeature);

var test = OmniaApi.WorkWith(Ctx.Omnia()).Features().GetFeature(id);

var url = test.Instances[2].Target;
var statusFromInstances = test.Instances[2].Status;

var status2 = OmniaApi.WorkWith(Ctx.Omnia()).Features().GetFeatureActivationStatus(id, url);

//Status will be activated in result "statusFromInstances" and "NotActivated " in "status2"

**Comment by PetterT2** [comment]
After activating a feature, GetFeatureActivationStatus gives different result when called from Job and WebApi.
Status is checked for the same ID and url both from a Job and from webapi, the Job always get status NotActivated, but webapi will get Activated after a while. 

Expected: Same result/return value from calls initiated in a Job and WebApi

**Comment by andtii** [comment]
@PetterT2 This is a bug, the server was not using the targetUrl parameter provider instead it was using the url of the created clientcontext which in Jobs is based on the tenant authority url. This has now been fixed and will be in the Cycle 8 release
