### ISSUE TITLE
OmniaApi.WorkWith(Ctx.Omnia()).Lists(Ctx).AddFileToList

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#52]
What is the **fileType** parameter used for? It seems to not be in use at all

**Comment by andtii** [comment]
@khdi I checked this and it seems safe to remove, it will be a breaking change but i cant se anyone using this? Option is to depricate

**Comment by andtii** [comment]
Added as depricated, will be removed in a couple of months

**Comment by baseic** [comment]
Clarification: New method added that does not contain the fileType parameter. The old one is depricated
