### ISSUE TITLE
CreateUserClientContext failes - throws exception

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#53]
Calling  Omnia.Foundation.Extensibility.Core.SharePoint.SharePointContextProvider.CreateUserClientContext(Ctx.Omnia().TokenCacheKey, webUrl, Ctx.Omnia().LCID.ToString()); from service throws exception.

tokenCachekey: 2BCB1B232EBBC4AB148BBC45DDB3A345
webUrl: https://portal-x.omniadev.local/news
Ctx.Omnia().LCID.ToString() : "1033"

Throws exception with message: "Error when creating SharePoint Context"

All parameters to CreateUserClientContext are valid, ctx etc has just been used, web exists for url etc
(ctx.Web.Url is in fact: https://portal-x.omniadev.local/news)

**Comment by lapduongbkit** [comment]
Hi @PetterT2 ,

The last parameter must be "en-us" instead of "1033".
Please try it and let us know if there are any other problems!
