### ISSUE TITLE
Omnia Site Creation Owner

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation#56]
When creating a site with Omnia Site creation, the user is not only added to the Owners-group, but is also added with Full Permissions directly to the site.

This does not happen when using normal Self-service site creation

**Comment by lapduongbkit** [comment]
Hi Baseic,

The problem that you mention will just happen when create site (not site collection), and it will be like the below screenshot. The reason is that the site is created by app context so that SharePoint App user is added directly into the site permission. 

Its actually will not cause any logic problem from that specific permission.

![image](https://cloud.githubusercontent.com/assets/17378364/26190403/855f70a8-3bd3-11e7-814c-916a42de2057.png)

**Comment by baseic** [comment]
That is not how it works when we try it.

We only create Site Collections, and the user submitting the request is also added explicitly with Full Control to the site, see image below from 2013 on-prem

![image](https://cloud.githubusercontent.com/assets/4512466/26194083/90a20046-3bb7-11e7-9d06-72ae6ab90988.png)

**Comment by baseic** [comment]
@lapduongbkit  That is not how it works when we try it.

We only create Site Collections, and the user submitting the request is also added explicitly with Full Control to the site, see image below from 2013 on-prem

![image](https://cloud.githubusercontent.com/assets/4512466/26194083/90a20046-3bb7-11e7-9d06-72ae6ab90988.png)

**Comment by PetterT2** [comment]
This is the creation request we build:

```
                var baseRequest = this.siteRequestsService.initSiteRequestBaseOnTemplate(result.siteTemplate);

                var baseUrl = Utils.ensureTrailingSlash(Utils.getServerUrl(_spPageContextInfo.siteAbsoluteUrl) + result.siteTemplate.location);
                this.getFreeUrlforTitle(baseUrl, this.newSiteInfo.title).then((freeUrlTitle) => {
                    baseRequest.location = baseUrl;
                    baseRequest.title = this.newSiteInfo.title;
                    baseRequest.owners = [];
                    baseRequest.owners.push(this.newSiteInfo.admins[0].key);
                    baseRequest.description = this.newSiteInfo.description;

                    baseRequest.urlValidateResult = {
                        urlValidated: true,
                        existedWeb: false,
                        invalidUrl: false,
                        validateUrlInProcess:false
                    }
                    baseRequest.lcid = result.siteTemplate.lcid;
                    baseRequest.timeZone = result.siteTemplate.defaultTimeZone;
                    baseRequest.url = freeUrlTitle;
                    baseRequest.keywords = [];
                    baseRequest.members = [];
                    baseRequest.readers = [];

                    this.siteRequestsService.addSiteRequest(baseRequest, (request) => {
                        this.waitForCreate(request, () => {
                            this.isCreatingSite = false;

                            this.createdUrl = baseUrl + freeUrlTitle;
                        }, () => {
                            this.isCreatingSite = false;
                            this.errorLog.push("No error information from log");
                            this.queueService.getTransactionLogs(request.transactionId, (transactionLogResult) => {
                                if (transactionLogResult.isSuccess) {
                                    this.errorLog = [];
                                    for (var log of transactionLogResult.data.messages) {
                                        this.errorLog.push(log.message);
                                    }
                                }
                            });
                        });
                    });

                });
```
We are waiting for the typescript service to be exposed, so this might be a problem that has been fixed in your ts-service since code extraction. But it seems to be information generated serverside. See issue #58
