### ISSUE TITLE
Typescript service(s) not exposed to extensibility

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#58]
SiteTemplateService and SiteRequestService is not available for use by Extensions.
Need if for example generating custom UI for Site creation by template.

**Comment by khdi** [comment]
Expose the models for site requests and site templates, move them to the same namespace called Sites.

Expose a SitesService with this API:

public addSiteRequest = (siteRequest: Sites.ISiteRequest, callback: (result: Sites.ISiteRequestResult) => void): void

public checkRequestStatus = (siteRequestId: string, callback: (siteRequestStatus: number) => void, reject?: (error: any) => void): void

public initSiteRequest = (siteTemplate: SiteTemplate.ISiteTemplate): Sites.ISiteRequest

public getSiteProvisioningResult = (spUrl: string, callback: (siteProvisioningResult: Sites.ISiteProvisioningResult) => void): void

public getAllSiteTemplates = (callback: (siteTemplates: Array<Sites.ISiteTemplate>) => void): void

public getSiteTemplates = (targetSiteUrl: string, templateGroup: string, callback: (siteTemplates: Array<Sites.ISiteTemplate>) => void): void

public getSiteTemplateWithValidation = (targetSiteUrl: string, siteTemplateId: string, callback: (siteCreationValidationResult: Sites.ISiteCreationValidation) => void): void
