### ISSUE TITLE
delayBootstrap not called

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#59]
Trying to use the promise approach to bootstrapping:

Component:

  insertUsingSelector: { instanceId: "29709eff-d015-493c-9fc3-37af5df95d57", cssClass: "removeFlickerDummy", insertTo: "#ms-microfeeddiv", delayBootstrap: NewsfeedSettingControl.findBootstrapElement },
    enableAot: true,
-----------------------------------------------------------
    static findBootstrapElement = ():Promise<void> => {
        var promise = new Promise<void>((resolver, rejector) => {
            NewsfeedSettingControl.waitForBootstrapElement(resolver);
        });
        return promise;
    }

findBootstrapElement is never invoked, so no promise is returned to Omnia.

**Comment by baseic** [comment]
The error was due to the control being blocked in the customer project. No Omnia bug
