### ISSUE TITLE
Support provision framework for List and Field

### ISSUE THREAD

**Issue by Ddv0623** [preciofishbone/Omnia-Foundation#69]
Support edit Sharepoint List variable EnableFolderCreation, When provisioning List. Right now, i need to provision list then edit these value.
And support set default value for Field.

**Comment by andtii** [comment]
@Ddv0623 thnx for the suggestions. We will add the EnableFolderCreation property but regarding the DefaultValue already support setting the default value for fields or is there something else?

```
[NoteField(id: "59C59A61-7F0E-494D-825B-E8CBB5B5B3CE", internalName: "name",
           Title = "Test", Description = "Test",
           Group = "Test", Required = true, DefaultValue ="This is a default value")]
```
