### ISSUE TITLE
omf-csom-people-picker - out of order results

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#70]
When using the people picker in a slow environment several request to resolve the user seems to be sent while typing the user information. 
Some times the results seems to arrive out of order, i.e. first displaying a more specific result and suddenly shifting to several possibilities (less specific result).

One option would be to make sure the arrived result is related to current search string or  not allow it to over write if already displaying a result for a more specific search string.

**Comment by andtii** [comment]
The correct behavior is to abort the xhr request when a new starts

**Comment by khdi** [comment]
This fix also need to be applied for taxonomy picker
