### ISSUE TITLE
"Update All" features in Omnia admin is not working

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#73]
NuGet Version 1.0.5421, seems to be on site level

**Comment by andtii** [comment]
@PetterT2 Could you provide some more information! What is not working? Exception?

**Comment by PetterT2** [comment]
The spinner does start to spin on neither the "Update All"-btn nor on any of the other "Update"-btns. Note it's only on site level we see this, it's working on Site Collection and tenant levels.

**Comment by khdi** [comment]
@PetterT2  This should be reported as an AM issue, link to Trello : https://trello.com/c/uqQvp0hl/1067-update-all-features-in-omnia-admin-is-not-working
