### ISSUE TITLE
Admin access check - Permissions not enforced in ng2 admin controls

### ISSUE THREAD

**Issue by PetterT2** [preciofishbone/Omnia-Foundation#75]
Trying to navigate to a known route for ng1 control on which user does not have permissions, gives error.
Trying to navigate to a known route for ng2 control on which user does not have permissions, gives no error/access denied.

See attachments
![admin_access_ng1](https://user-images.githubusercontent.com/25247344/27868709-dcc4c790-619d-11e7-8569-70d9dfa1a189.png)
![admin_access_ng2](https://user-images.githubusercontent.com/25247344/27868715-e18a2a7c-619d-11e7-970a-1cfeb5400e76.png)

**Comment by tuannla07** [comment]
@PetterT2  Thanks for your feedback, to make admin control enforced permission you should make your class extend from OmniaAdminPermissionBase
`import { AdminAuthorizationService, OmniaAdminPermissionBase } from "@Omnia/Foundation/Extensibility";

constructor( @Inject(AdminAuthorizationService) public authorizationService: AdminAuthorizationService) 
 {
        super(authorizationService, authorizedRoles);
        if (this._isAuthorized)
          //TODO
 }`
