### ISSUE TITLE
Using same "namespace" in different extension projects

### ISSUE THREAD

**Issue by Hulabandula** [preciofishbone/Omnia-Foundation#98]
Hi! if one copies e.g. a pipe.ts file to another extension project that is to be deployed to the same tenant and one does not change the name of the class, then it will override existing functionality in the bundle.js. Does the omnia bundling not add unique prefix in bundling if from other extension project?

**Comment by andtii** [comment]
@Hulabandula the webpack config today is basing the uniqueness of the modules by the folder path starting from "TenantResources" which could end up in multiple extensions having the same path. We are looking at isolating this by adding extensionid isolation to fix this issue. In the meantime the best way to make it unique is to have a root folder with a more unique name like "TenantResources\mycustomsolutionname" and then have the rest of logic inside that folder.

**Comment by Hulabandula** [comment]
True I found that out so now my extensions have moved in to a unique folder.
